language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = 'hhvm' ]; then composer remove doctrine/dbal --dev --no-interaction --no-update; fi;"
  - composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=dev-master
